### ISSUE TITLE
Use proper logging

### ISSUE THREAD

**Issue by empijei** [empijei/wapty#18]
All logging operations and all calls to fmt.Print.* or log.* should be changed to use the [lg package](https://github.com/empijei/wapty/tree/master/cli/lg)

**Comment by duckoder** [comment]
Hi, @empijei. I think I can help you with this.

**Comment by duckoder** [comment]
@empijei all calls should changed expect tests, rights ?

**Comment by empijei** [comment]
I don't think many test read the output of functions to stdout, so you just probably need to replace calls to log or Println to calls to lg.Debug/Info/Error

**Comment by duckoder** [comment]
Here is PR, https://github.com/empijei/wapty/pull/20 Currently, it's WIP stage

**Comment by empijei** [comment]
If a call to log is followed by a panic or if you find calls to panic just please call lg.Fail instead.

**Comment by empijei** [comment]
fixed with PR #20 , closing
