### ISSUE TITLE
`wapty help`

### ISSUE THREAD

**Issue by silverweed** [empijei/wapty#4]
This is likely a long-term goal, but I'm dropping it here.

It would be nice to have a `wapty help` command that mimics `go help`: without args, it should just display all the available modules and their purpose, whereas `wapty help <module>` should display the detailed usage of the single module.

AFAIK the `go help` command uses a combination of templates and per-package global structs holding the command information. We should probably copy that design for this task.

**Comment by empijei** [comment]
Good idea, will do.

**Comment by empijei** [comment]
I think [commit 0023e9a661](https://github.com/empijei/wapty/commit/0023e9a661b8cc3f1d47081119fe940069d7a9ef) fixes this.
