### ISSUE TITLE
Fix badges in ROADMAP

### ISSUE THREAD

**Issue by empijei** [empijei/wapty#9]
Find a way to correctly display coverage badges in [ROADMAP.md](https://github.com/empijei/wapty/blob/master/ROADMAP.md)

The badges now show a "coverage error" message:
![image](https://user-images.githubusercontent.com/1256049/31070518-fa398adc-a760-11e7-914b-6dc4c1eb30eb.png)

but they should show a percentage of the package coverage:
![image](https://user-images.githubusercontent.com/1256049/31070545-0a89679a-a761-11e7-8b08-ef46a7f02a2b.png)

**Comment by gromethean** [comment]
I'm looking into this :)

**Comment by empijei** [comment]
@jamesday7 please take a look [here](https://github.com/vieux/gocover.io/issues/27) as it should fix the issue once [my pr](https://github.com/vieux/gocover.io/pull/31) gets accepted. 

If it does fix the issue at hand I don't want you to waste any precious time on this. Keep hacking where FOSS needs you the most! :grin:

**Comment by gromethean** [comment]
@empijei yeah, it's completely baffled me because it seemed to work for me for 10 minutes and stopped.

**Comment by empijei** [comment]
Yup, it's been a while I have been observing this weird behavior, I can build the markdown correctly locally, but github caching seemed to not agree.

**Comment by empijei** [comment]
I confirm this is now fixed.
